refactor(core): use zod to validate schemas
rivet-dev/agentos pull request #448
Opened 2024-07-06 16:01 UTC by jog1t

**Before testing, please remove all related cache (especially .opengb/cache.json)**
What's interesting, enabling a schema validation for modules (here: https://github.com/rivet-gg/opengb/blob/338e554d0a3758b7c29ada56f74b384b87c346a4/src/runtime/context.ts#L85 and here https://github.com/rivet-gg/opengb/blob/338e554d0a3758b7c29ada56f74b384b87c346a4/src/runtime/context.ts#L107-L120) causes registry tests to fail, as most of them are reporting fail-positive statuses right now.

2024-07-08 16:57 UTC, NathanFlurry commented
@jog1t you can change `CACHE_VERSION` in `src/build_state/cache.ts`

2024-07-08 17:37 UTC, NathanFlurry requested changes, later dismissed
notes:
- remove all uses of tjs (don't worry about deprecated requestConfig)
- export json schema to meta.json (where userConfigSchema was)
- fix lints
- fix `--strict-schemas` flag to be `--no-strict-schemas`
- config/deps.ts is empty
- remove artifacts/build_schema.ts
- revert src/template/script.ts to og behavior
- replace parseAsync with safeParseAsync

2024-07-11 17:18 UTC, MasterPtato approved these changes

2024-07-11 17:18 UTC, MasterPtato commented on src/build/schema/serializer.ts
> +const tsLib = Deno.readTextFileSync(import.meta.dirname + "/schema_ts_lib.ts");
This likely won't compile in CI, you'll have to add this file to the generated build artifacts and import it from there

2024-07-11 17:18 UTC, MasterPtato requested changes, later dismissed
See comments

2024-07-17 04:36 UTC, NathanFlurry commented
### Merge activity

* **Jul 17, 12:36 AM EDT**: @NathanFlurry started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/rivet-gg/opengb/448).

2024-07-17 05:00 UTC, merged